export const LOAD_STUDENTS_STATISTICS = 'LOAD_STUDENTS_STATISTICS';
export const LOAD_STUDENTS = 'LOAD_STUDENTS';
export const COUNT_STUDENTS = 'COUNT_STUDENTS';
export const LOAD_STUDENT = 'LOAD_STUDENT';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SEARCH_STUDENTS = 'SEARCH_STUDENTS';
export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';
