export const LOAD_STUDENTS_STATISTICS = 'LOAD_STUDENTS_STATISTICS';
export const LOAD_STUDENTS = 'LOAD_STUDENTS';
export const COUNT_STUDENTS = 'COUNT_STUDENTS';
export const SELECT_STUDENT = 'SELECT_STUDENT';
